### PR TITLE
Create AllStackOperations.c

### PR DESCRIPTION
**Pull request by dp981**
Please accept my Pull request for this Program. Thanks A lot.

I am creating a pull request for...

- [ ] New algorithm

### CODE REVIEW

**Review by abranhe — APPROVED** [review]
Thanks so much for your contribution to [The All ▲lgorithms Project](https://github.com/allalgorithms). Without people like you submitting Pull Requests we couldn't run this project. You rock!

**Comment by dp981** [comment]
Hey, Can you all the pull requests unde @dp981 to Hacktober- accepted label
please. It will really help.

**Comment by abranhe** [comment]
@dp981 is not necessary!

According to Hacktoberfest a pull request is considered valid if it has the hacktoberfest-accepted or if the pull request have been approved.

This pull request have been approved!

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by dp981** [comment]
Looking Forward to adding more Algorithms and contributing toward your
Repositories

**Pull request merged**
